name: Release
run-name: ${{ github.event.head_commit.message }} - ${{ github.ref_name }} - ${{ github.event.head_commit.timestamp }}

on:
  push:
    branches:
      - qa
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
